# Server
server.port=8080


# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/violetchat
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=false

# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Разрешить циклические зависимости
spring.main.allow-circular-references=true

# Статика
spring.web.resources.static-locations=classpath:/static/
spring.web.resources.add-mappings=true

# Логирование
logging.level.com.violetchat=DEBUG